"""initial tables setup

Revision ID: 03b149f5d64e
Revises: 2da2c0ccb068
Create Date: 2023-09-22 11:13:32.058806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b149f5d64e'
down_revision = '2da2c0ccb068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
